@startuml

title __CHECKBOXTREE's Class Diagram__\n

  namespace org.openstreetmap.gui.jmapviewer {
    namespace checkBoxTree {
      class org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeData {
          + CheckBoxNodeData()
          + CheckBoxNodeData()
          + CheckBoxNodeData()
          + getAbstractLayer()
          + getText()
          + isSelected()
          + setAbstractLayer()
          + setSelected()
          + toString()
      }
    }
  }
  

  namespace org.openstreetmap.gui.jmapviewer {
    namespace checkBoxTree {
      class org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor {
          {static} - serialVersionUID : long
          + CheckBoxNodeEditor()
          + addNodeListener()
          + getCellEditorValue()
          + getTreeCellEditorComponent()
          + isCellEditable()
      }
    }
  }
  

  namespace org.openstreetmap.gui.jmapviewer {
    namespace checkBoxTree {
      class org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodePanel {
          + check : JCheckBox
          - label : JLabel
          {static} - serialVersionUID : long
          + CheckBoxNodePanel()
          + getData()
          + getLabel()
          + setData()
          + setSelected()
      }
    }
  }
  

  namespace org.openstreetmap.gui.jmapviewer {
    namespace checkBoxTree {
      class org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeRenderer {
          - defaultRenderer : DefaultTreeCellRenderer
          - selectionBackground : Color
          - selectionForeground : Color
          - textBackground : Color
          - textForeground : Color
          + CheckBoxNodeRenderer()
          + addNodeListener()
          + getTreeCellRendererComponent()
          # getPanel()
      }
    }
  }
  

  namespace org.openstreetmap.gui.jmapviewer {
    namespace checkBoxTree {
      class org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxTree {
          {static} - serialVersionUID : long
          + CheckBoxTree()
          + CheckBoxTree()
          + CheckBoxTree()
          + CheckBoxTree()
          + add()
          + addLayer()
          + addLayer()
          + addNodeListener()
          {static} + createNode()
          {static} + createNodeData()
          {static} + data()
          + deleteAllNodesChildren()
          {static} + main()
          + rootData()
          + rootLayer()
          + rootNode()
          + searchNode()
          + searchNode()
          {static} - add()
          {static} - changeParents()
          {static} - childStatus()
          {static} - data()
          {static} - node()
          {static} - nodeChanged()
          {static} - setChildrens()
      }
    }
  }
  

  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeData o-- org.openstreetmap.gui.jmapviewer.AbstractLayer : layer
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor .up.|> javax.swing.tree.TreeCellEditor
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor -up-|> javax.swing.AbstractCellEditor
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor o-- org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeRenderer : renderer
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor o-- org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxTree : theTree
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodePanel -up-|> javax.swing.JPanel
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodePanel o-- org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeData : data
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeRenderer .up.|> javax.swing.tree.TreeCellRenderer
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeRenderer o-- org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodePanel : panel
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxTree -up-|> javax.swing.JTree
  org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxTree o-- org.openstreetmap.gui.jmapviewer.checkBoxTree.CheckBoxNodeEditor : editor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
